### PR TITLE
Setup Docker for notebooks

### PR DESCRIPTION
**Pull request by ruebot**
- Add Dockerfile,
- Add required nltk data
- Add instructions in README

<hr />

Test:
 - Instructions in the README should cover getting it fired up
 - Once it's up, navigate to http://127.0.0.1:8888/whatever-the-token-is
 - Step through the notebook(s)
 - Should hopefully get all of the below images:

screenshot from 2019-03-01 15-26-36

screenshot from 2019-03-01 15-26-53

screenshot from 2019-03-01 15-27-06

screenshot from 2019-03-01 15-27-21

screenshot from 2019-03-01 15-27-38

screenshot from 2019-03-01 15-27-57

screenshot from 2019-03-01 15-28-11

screenshot from 2019-03-01 15-28-23

### CODE REVIEW

**Comment by ianmilligan1** [comment]
Great, thanks @ruebot – this looks awesome (I got to see a sneak peak of it in real life over Nick's shoulder this afternoon).

I will probably test this on Monday (or this weekend if I can find a moment, but probably Monday). I think a notebook that has the data variables blank makes sense to me, but curious to hear @greebie's thoughts as the repo's original architect.

**Comment by greebie** [comment]
I agree with removing the second notebook.  The only reason it was there in the first place was to show the community what it looked like without having to clone and run Jupyter. It has no other purpose.

I also agree the next step is to include some kind of markup for the things we want variable in auk.  Collection is obvious, but I also things like the data folder, descriptive information (title, organization, etc. if possible) and maybe even consider a partner logo.

**Comment by greebie** [comment]
Only question in my mind is whether to remove ggplot from the dep list.  I saw you added the hack, so I'm fine with keeping it. The only advantage is that the ggplot graphs etc. are more pretty than matplotlib. None of the scripts use ggplot as it stands.

**Comment by ianmilligan1** [comment]
Let’s keep things as simple as we can, in case our WASAPI partners ever increase. I’d be inclined to avoid things like partner logos, etc. and just keep to collection ID and perhaps collection title.

**Comment by greebie** [comment]
Okay - this is good to merge on my end.  Ggplot issue is taken care of in later PR.

**Pull request merged**
