### PR TITLE
Fix malformed JSON for collection ID

### PR DESCRIPTION
**Pull request by ianmilligan1**
@SamFritz and I were doing some local testing on master and got the following error (on both of our systems):

screen shot 2019-03-06 at 4 28 53 pm

Somewhere along the line when the collection ID was added in, an escape went mixing which threw off the full cell. This branch works on both of our systems now. 

screen shot 2019-03-06 at 4 29 49 pm

I'm not sure how this happened as it was definitely working locally earlier. 

@greebie is currently working on a branch though. So maybe you just want to make sure that it works, so this is more just to have a branch that works (I have it at draft right now).

### CODE REVIEW

**Comment by ianmilligan1** [comment]
Ok I have marked this as ready for review. @greebie can you review + merge?

**Comment by ianmilligan1** [comment]
Or actually, I guess @SamFritz can review too since she was in the room and verified that this works! 😄

**Comment by SamFritz** [comment]
I recloned the repo so I'll be able to do a walk through with a fresh slate. Will let you know if anything seems amiss.

**Comment by greebie** [comment]
Almost there. Just fixing a few tiny bugs and we should be good to go in the next commit..

**Comment by SamFritz** [comment]
this now works for me!

**Pull request closed without merging**
